# server {
#     listen 80;
#     server_name learnspire.ai;
#
#     # Point to the 'dist' folder created after the build
#     root C:/Users/akash/WebstormProjects/learnspire-Landing-page/dist;
#     index index.html;
#
#     location / {
#         try_files $uri /index.html;  # Serve index.html for routes handled by React
#     }
#
#     location /static/ {
#         root C:/Users/akash/WebstormProjects/learnspire-Landing-page/dist;  # Serve static assets
#     }
#
#     error_page 404 /index.html;  # Redirect 404 to index.html for React Router
# }
